version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/data
  redis:
    image: "redis:alpine"
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24