apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskselfdemo
  namespace: default
  labels:
    app: flaskselfdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskselfdemo
  template:
    metadata:
      labels:
        app: flaskselfdemo
    spec:
      containers:
      - name: flaskselfdemo
        image: ccr.ccs.tencentyun.com/tke-chaos/flask_self_demo:1.0.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100M
          requests:
            cpu: 100m
            memory: 100M
---

apiVersion: v1
kind: Service
metadata:
  name: flaskselfdemo-service
  namespace: default
  labels:
    app: flaskselfdemo
    app: flaskselfdemo-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31918
    targetPort: 80
    protocol: TCP
  selector:
    app: flaskselfdemo
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flaskselfdemo-ingress
  annotations:
    description: flaskselfdemo-ingress
    ingress.cloud.tencent.com/direct-access: "false"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: flask.self.demo
    http:
      paths:
      - backend:
          serviceName: flaskselfdemo-service
          servicePort: 80
        path: /v1
        pathType: ImplementationSpecific