apiVersion: v1
data:
  username: YWRtaW4=
  password: YWRtaW4zMjE=
kind: Secret
type: Opaque
metadata:
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "flaskselfdemo.labels" . | nindent 4 }}
  name: {{ include "flaskselfdemo.fullname" . }}
